export const listOfAllExercises = [
  "Bench press",
  "Deadlifts",
  "Treadmill",
  "Elliptical machine",
  "Stationary bike",
  "Rowing machine",
  "Jump rope",
  "Stair climber",
  "Swimming",
  "Distance Run",
  "Cycling",
  "High-intensity interval training (HIIT)",
  "CrossFit",
  "Spinning",
  "Push-ups",
  "Dumbbell bench press",
  "Pull-ups",
  "Bent-over rows",
  "Dumbbell rows",
  "Overhead press",
  "Dips",
  "Bicep curls",
  "Lateral raises",
  "Lat pulldowns",
  "Face pulls",
  "Skull crushers",
  "Hammer curls",
  "Push press",
  "Incline bench press",
  "Cable flyes",
  "Dumbbell pullovers",
  "Dumbbell shoulder press",
  "Squats",
  "Lunges",
  "Leg press",
  "Leg curls",
  "Goblet squats",
  "Leg extensions",
  "Box jumps",
  "Calf raises",
  "RDL's",
  "Sumo squats",
  "Bulgarian split squats",
  "Hip thrusts",
  "Step-ups",
  "Good mornings",
  "Pistol squats",
  "Hack squats",
  "Glute bridges",
  "Smith machine squats",
  "Smith machine lunges",
  "Planks",
  "Russian twists",
  "Bicycle crunches",
  "Leg raises",
  "Sit-ups",
  "V-ups",
  "Medicine ball slams",
  "Hanging leg raises",
  "Woodchoppers",
  "Side planks",
  "Swiss ball pikes",
  "Ab wheel rollouts",
  "Cable crunches",
  "Hanging knee raises",
  "Decline sit-ups",
  "Reverse crunches",
  "L-sit holds",
  "Turkish get-ups",
  "Dead bugs",
  "Windshield wipers",
  "Preacher curls",
  "Burpees",
  "Mountain climbers",
  "Bodyweight squats",
  "Burpee pull-ups",
  "Wall sits",
  "Tuck jumps",
  "Kettlebell swings",
  "Farmer's carries",
  "Sled pushes",
  "Tire flips",
  "Parkour training",
  "Handstands",
  "Human flag",
  "Muscle-ups",
  "Planche",
  "L-sit",
  "Monkey bars",
  "Yoga",
  "Pilates",
  "Foam rolling",
  "Static stretching",
  "Dynamic stretching",
  "Resistance band stretches",
  "Hip circles",
  "Butterfly stretch",
  "Cat-cow stretch",
  "Child's pose",
  "Pigeon pose",
  "Cobra pose",
  "Downward-facing dog",
  "Standing quad stretch",
  "Supine hamstring stretch",
  "Figure four stretch",
  "Wrist stretches",
  "Depth jumps",
  "Jumping lunges",
  "Clap push-ups",
  "Broad jumps",
  "Vertical jumps",
  "Plyo push-ups",
  "Plyo step-ups",
  "Medicine ball throws",
  "Chest fly machine",
  "Cable bicep curls",
  "Cable tricep pushdowns",
  "Leg abduction machine",
  "Leg adduction machine",
  "Pec deck machine",
  "Seated calf raise machine",
  "Seated rows",
  "TRX suspension trainer",
  "Bosu ball exercises",
  "Kettlebell exercises",
  "Bulgarian bag training",
  "Medicine ball exercises",
  "Battle ropes",
  "Resistance bands",
  "Sandbag training",
  "Indian club swinging",
  "Parallettes exercises",
  "Agility ladder drills",
  "Plyometric boxes",
  "ViPR exercises",
  "Tennis drills",
  "Golf swings",
  "Soccer dribbling drills",
  "Basketball shooting practice",
  "Baseball pitching drills",
  "Swimming strokes",
  "CrossFit WODs",
  "Wrestling drills",
  "MMA training drills",
  "Volleyball spikes",
  "Strongman training",
  "Powerlifting",
  "Power cleans",
  "Clean and jerks",
  "Olympic weightlifting",
  "Calisthenics",
  "Gymnastics training",
  "Martial arts conditioning",
  "Yoga for athletes",
  "Suspension training (TRX)",
  "High-altitude training",
  "CrossFit workouts",
  "Senior fitness exercises",
  "Soccer passing drills",
  "Football agility drills",
  "Basketball dribbling drills",
  "Volleyball serving drills",
  "Hockey stickhandling drills",
  "Rugby tackling drills",
  "Ultimate Frisbee throws",
  "Lacrosse shooting drills",
  "Baseball fielding practice",
  "Softball pitching drills",
  "Cable pullovers",
  "Single-arm pullovers",
  "Chest-supported rows",
  "Single-arm rows",
  "Single-arm tricep extensions",
  "Dumbbell front raises",
  "Rear delt flyes",
  "Reverse grip curls",
  "Forearm curls",
  "Jump squats",
  "Close-grip bench press",
  "Shrugs",
  "Chest press machine",
  "Ab crunch machine",
  "Sissy squats",
  "Arnold press",
  "Front squat",
  "Back extension machine",
  "Assisted Pull-ups",
  "Assisted Dips",
  "Zercher Squat",
  "Pause Squats",
  "Anderson Squats",
  "Deficit Deadlifts",
  "Snatch",
  "Pendlay Rows",
  "Behind-the-Neck Press",
  "Reverse Lunges",
  "Kettlebell Squats",
];
